lista = ["Japón", "Corea del sur","Alemania", "Maldivas", "Canada"]
print(lista)
print(sorted(lista))
print(lista)
print(sorted(lista, reverse=True))
print(lista)
lista.reverse()
print(lista)
lista.reverse()
print(lista)
lista.sort()
print(lista)
lista.sort(reverse=True)
print(lista)
